_wandb:
    value:
        cli_version: 0.23.1
        e:
            7yc9i359kf8vvhoe79sorlam3538ngn9:
                email: zengzhuoxi@gmail.com
                executable: /home/derekszen/Projects/SALT-VLA/.venv/bin/python
                git:
                    commit: 5719589102f5c6f6e7159fdbcacf022c094e2087
                    remote: git@github.com:derekszen/SALT-VLA.git
                host: omarchyNeptune
                os: Linux-6.17.9-arch1-1-x86_64-with-glibc2.42
                program: -m src.train
                python: CPython 3.12.12
                root: /home/derekszen/Projects/SALT-VLA
                startedAt: "2025-12-27T17:42:54.554590Z"
                writerId: 7yc9i359kf8vvhoe79sorlam3538ngn9
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 63
            "2":
                - 1
                - 11
                - 41
                - 49
                - 63
            "3":
                - 13
            "4": 3.12.12
            "5": 0.23.1
            "6": 4.57.3
            "12": 0.23.1
            "13": linux-x86_64
